vich_uploader:
    db_driver: orm

    mappings:
        liquids_images:
            uri_prefix: /images/liquids
            upload_destination: '%kernel.project_dir%/public/images/liquids'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
